enableGlobalCache: true

httpProxy: "http://127.0.0.1:7078"

httpsProxy: "http://127.0.0.1:7078"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs
